word_list = {
    'ABLE':'Having what is required (e.g., money or skills) to do something.',
    'ANGRY':"Being very annoyed or upset.",
    'BAD':"Unpleasant; causing problems.",
    'BEST':"Superior to all others.",
    'BETTER':"Recovered after an illness or injury.",
    'BIG':"Large in size.",
    'BUSY':"Occupied with activities or work.",
    'CLEAR':"Very obvious.",
    'DIFFERENT': 'Not the same.',
    'EARLY':"At or near the beginning of a period of time.",
    'EASY': 'Not difficult.',
    'EXCELLENT': 'Extremely good.',
    'FREE':'Not costing money.',
    'FULL':'Containing as much as possible with no empty space.',
    'GOOD':'Pleasant; causing no problems.',
    'GREAT':"Better than good; of a very high quality.",
    'HARD':'Solid; not soft.',
    'HIGH':'Being a great distance from the bottom.',
    'HUGE':'Extremely big.',
    'IMPORTANT':'Very meaningful, valuable or powerful.',
}