word_list = {
    'ABLE':'Having what is required (e.g., money or skills) to do something.\n',
    'ANGRY':"Being very annoyed or upset.\n",
    'BAD':"Unpleasant; causing problems.\n",
    'BEST':"Superior to all others.\n",
    'BETTER':"Recovered after an illness or injury.\n",
    'BIG':"Large in size.\n",
    'BUSY':"Occupied with activities or work.\n",
    'CLEAR':"Very obvious.\n",
    'DIFFERENT': 'Not the same.\n',
    'EARLY':"At or near the beginning of a period of time.\n",
    'EASY': 'Not difficult.\n',
    'EXCELLENT': 'Extremely good.\n',
    'FREE':'Not costing money.\n',
    'FULL':'Containing as much as possible with no empty space.\n',
    'GOOD':'Pleasant; causing no problems.\n',
    'GREAT':"Better than good; of a very high quality.\n",
    'HARD':'Solid; not soft.\n',
    'HIGH':'Being a great distance from the bottom.\n',
    'HUGE':'Extremely big.\n',
    'IMPORTANT':'Very meaningful, valuable or powerful.\n',
    'INTERNATIONAL': 'Involving two or more countries.\n',
    'LATE':'Happening at or near the end of a period of time.\n',
    'LITTLE':'Small in size or amount.\n',
    'LOCAL':'Relating to a specific area such as a neighbourhood or city.\n',
    'LONG':'Measuring a great distance from one end to the other.\n',
    'LOW':'Less than average height from top to bottom \n or to the top from the ground..\n',
    'LOUD':'Making a lot of noise.\n',
    'MAJOR':'Very important, serious or big.\n',
    'NATIONAL':'Involving an entire country.\n',
    'NEW':'Recently created, bought or rented.\n',
    'OLD':'Having existed for a long time.\n',
    'ONLY':'Alone in a category; having no others like it.\n',
    'OPEN':'Not closed; able to be entered.\n',
    'OTHER':"Referring to a thing or person that's different \n from the one that's already known or mentioned.\n",
    'PERSONAL':'Belonging to or affecting a particular person.\n',
    'POLITICAL':'Relating to government or politics.\n',
    'POSSIBLE':'Able to happen, be done or exist.\n',
    'PUBLIC':'Relating to most of the people in a city, country, etc.\n',
    'REAL':'Not fake or artificial.\n',
    'RECENT':'Having happened or started not long ago.\n',
    'RIGHT':'Socially or morally correct.\n',
    'SMALL':'Little in amount or size.\n',
    'SOCIAL':"Happy to talk to and be around people.\n",
    'SPECIAL':"Different from what is normal (often in a good way).\n",
    'STRONG':"Mentally or physically powerful.",
    'SURE':"Not having any doubt; certain.\n",
    'TRUE':'In agreement with facts.\n',
    'WEIRD':'Strange or unusual.\n',
    'WHOLE':'Complete; all of the parts.\n',
    'YOUNG':'In an early stage of life.\n'
}