word_list = {
    'ABLE':'Having what is required (e.g., money or skills) to do something.',
    'ANGRY':"Being very annoyed or upset.",
    'BAD':"Unpleasant; causing problems.",
    'BEST':"Superior to all others.",
    'BETTER':"Recovered after an illness or injury.",
    'BIG':"Large in size.",
    'BUSY':"Occupied with activities or work.",
    'CLEAR':"Very obvious.",
    'DIFFERENT': 'Not the same.',
    'EARLY':"At or near the beginning of a period of time.",
    'EASY': 'Not difficult.',
    'EXCELLENT': 'Extremely good.',
    'FREE':'Not costing money.',
    'FULL':'Containing as much as possible with no empty space.',
    'GOOD':'Pleasant; causing no problems.',
    'GREAT':"Better than good; of a very high quality.",
    'HARD':'Solid; not soft.',
    'HIGH':'Being a great distance from the bottom.',
    'HUGE':'Extremely big.',
    'IMPORTANT':'Very meaningful, valuable or powerful.',
    'INTERNATIONAL': 'Involving two or more countries.',
    'LATE':'Happening at or near the end of a period of time.',
    'LTTLE':'Small in size or amount.',
    'LOCAL':'Relating to a specific area such as a neighbourhood or city.',
    'LONG':'Measuring a great distance from one end to the other.',
    'LOW':'Not rising a great distance.',
    'LOUD':'Making a lot of noise.',
    'MAJOR':'Very important, serious or big.',
    'MATIONAL':'Involving an entire country.',
    'NEW':'Recently created, bought or rented.',
    'OLD':'Having existed for a long time.',
    'ONLY':'Alone in a category; having no others like it.',
    'OPEN':'Not closed; able to be entered.',
    'OTHER':"Referring to a thing or person that's different from the one that's already known or mentioned.",
    'PERSONAL':'Belonging to or affecting a particular person.',
    'POLITICAL':'Relating to government or politics.',
    'POSSIBLE':'Able to happen, be done or exist.',
    'PUBLIC':'Relating to most of the people in a city, country, etc.',
    'REAL':'Not fake or artificial.',
    'RECENT':'Having happened or started not long ago.',
    'RIGHT':'Socially or morally correct.',
    'SMALL':'Little in amount or size.',
    'SOCIAL':"Happy to talk to and be around people.",
    'SPECIAL':"Different from what is normal (often in a good way).",
    'STRONG':"Mentally or physically powerful.",
    'SURE':"Not having any doubt; certain.",
    'TRUE':'In agreement with facts.',
    'WEIRD':'Strange or unusual.',
    'WHOLE':'Complete; all of the parts.',
    'YOUNG':'In an early stage of life.'
}